package(default_visibility = ["//visibility:public"])

load("@rules_rust//rust:rust.bzl", "rust_binary")

rust_binary(
    name = "main_5_1_1",
    srcs = ["src/main_5_1_1.rs"],
)

rust_binary(
    name = "main_5_2_1",
    srcs = ["src/main_5_2_1.rs"],
)
