package(default_visibility = ["//visibility:public"])

load("@rules_rust//rust:rust.bzl", "rust_binary")

rust_binary(
    name = "main_4_4",
    srcs = ["src/main_4_4.rs"],
)

rust_binary(
    name = "main_4_2_1",
    srcs = ["src/main_4_2_1.rs"],
)

rust_binary(
    name = "main_4_2_6",
    srcs = ["src/main_4_2_6.rs"],
)

rust_binary(
    name = "main_4_3_1",
    srcs = ["src/main_4_3_1.rs"],
)

rust_binary(
    name = "main_4_3_2",
    srcs = ["src/main_4_3_2.rs"],
)
